news_sites:
  universal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.articulo-titulo a'
